volumes:
  ollama_data:
  pharmachat_data:

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      - ./model_files:/model_files
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
        - default

  pharmachat:
    build:
        context: ./pharmachat
        dockerfile: Dockerfile
    container_name: pharmachat
    volumes:
      - pharmachat_data:/root
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - default
networks:
  default:
    driver: bridge