volumes:
  ollama_data:

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
      - ./model_files:/model_files
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
        - default

  pharmachat:
    build:
        context: ./pharmachat
        dockerfile: Dockerfile
    container_name: pharmachat
    volumes:
      - ./pharmachat:/root
    depends_on:
      - ollama
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - default

  pharmachat_frontend:
    build:
      context: ./pharmachat_frontend
      dockerfile: Dockerfile
    container_name: pharmachat_frontend
    volumes:
      - ./pharmachat_frontend:/app
    depends_on:
      - pharmachat
    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - default

networks:
  default:
    driver: bridge