# k8s/pharmachat-frontend/pharmachat-frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pharmachat-frontend-service
spec:
  selector:
    app: pharmachat-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30000 # Choose a port in the 30000-32767 range
  type: NodePort