# k8s/pharmachat/pharmachat-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pharmachat-config
data:
  config.yaml: |
    # Content of your pharmachat/pharmachat/config/config.yaml
    # IMPORTANT: Update URLs to point to Kubernetes service names
    ollama_url: "http://ollama-service:11434" # Kubernetes service name