# k8s/pharmachat/pharmachat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pharmachat-service
spec:
  selector:
    app: pharmachat
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP