site_name: pharmachat
repo_url: https://github.com/ramonbotella/pharmachat
site_url: https://ramonbotella.github.io/pharmachat
site_description: A package to create an AI assintant whit pharmaceutical leaflets knowledge
site_author: Ramon Botella
edit_uri: edit/main/docs/
repo_name: ramonbotella/pharmachat
copyright: Maintained by <a href="https://ramonbotella.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ramonbotella/pharmachat
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pharmachat

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
